// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0


// TODO: https://github.com/okuda-seminar/log_service/issues/19#issue-2557614250
// - [Server] Make sqlc and gomock Executable within Docker Container
package dbgen

import (
	"context"
	"database/sql"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db: tx,
	}
}
