// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: log.sql

package dbgen

import (
	"context"
	"time"
)

const insertLog = `-- name: InsertLog :exec
INSERT INTO logs (
  log_level, date, destination_service, source_service, request_type, content
) VALUES (
  ?, ?, ?, ?, ?, ?
)
`

type InsertLogParams struct {
	LogLevel           string
	Date               time.Time
	DestinationService string
	SourceService      string
	RequestType        string
	Content            string
}

func (q *Queries) InsertLog(ctx context.Context, arg InsertLogParams) error {
	_, err := q.db.ExecContext(ctx, insertLog,
		arg.LogLevel,
		arg.Date,
		arg.DestinationService,
		arg.SourceService,
		arg.RequestType,
		arg.Content,
	)
	return err
}
