FROM golang:1.23

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

RUN go install go.uber.org/mock/mockgen@latest
RUN go get github.com/sqlc-dev/sqlc/cmd/sqlc@latest
RUN go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
ENV PATH="/go/bin:${PATH}"


COPY . .

CMD ["tail", "-f", "/dev/null"]