// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/domain/log_repository.go

// Package domain is a generated GoMock package.
package domain

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockILogRepository is a mock of ILogRepository interface.
type MockILogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockILogRepositoryMockRecorder
}

// MockILogRepositoryMockRecorder is the mock recorder for MockILogRepository.
type MockILogRepositoryMockRecorder struct {
	mock *MockILogRepository
}

// NewMockILogRepository creates a new mock instance.
func NewMockILogRepository(ctrl *gomock.Controller) *MockILogRepository {
	mock := &MockILogRepository{ctrl: ctrl}
	mock.recorder = &MockILogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILogRepository) EXPECT() *MockILogRepositoryMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockILogRepository) List(ctx context.Context) ([]Log, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]Log)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockILogRepositoryMockRecorder) List(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockILogRepository)(nil).List), ctx)
}

// Save mocks base method.
func (m *MockILogRepository) Save(ctx context.Context, log *Log) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockILogRepositoryMockRecorder) Save(ctx, log interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockILogRepository)(nil).Save), ctx, log)
}
