// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbgen

import (
	"time"
)

type Log struct {
	// Log_Level
	LogLevel string
	// Date
	Date time.Time
	// Destination_Service
	DestinationService string
	// Source_Service
	SourceService string
	// Request_Type
	RequestType string
	// Content
	Content string
}
