// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbgen

import (
	"time"
)

type CtrLog struct {
	// Event_Type
	EventType string
	// Created_At
	CreatedAt time.Time
	// Object_ID
	ObjectID string
}

type Log struct {
	// Log_Level
	LogLevel string
	// Date
	Date time.Time
	// Destination_Service
	DestinationService string
	// Source_Service
	SourceService string
	// Request_Type
	RequestType string
	// Content
	Content string
}
